version: '3'

services:
  backend:
    build: './backend'
    volumes:
      - ./backend:/app/price/backend
    ports:
      - 3000:3000
    environment:
      - "isDev=${isDev}"
    command: sh -c "npm run dev"
